### ISSUE TITLE
m4q & vegas.js

### ISSUE THREAD

**Issue by arjarn** [olton/dom#2]
I don't know if you can help me and sorry if I'm off topic ;)

Vegas is a Jquery / Zepto plugin to add background slider with lazy loading capacities (https://github.com/jaysalvat/vegas).

I'm attempting to make it m4q compatible.
This plugin add to DOM <div> with special class : vegas-slide..
After creating, m4q children function returns null if selecting DIV with vegas-slide class.
However all is ok when I'm using firefox inspector.

If I'm writing HTML code with DIV and vegas-slide class, children function is working.

I'm wondering if function work with dynamic elements...

**Comment by olton** [comment]
I fixed m4q. Download update from github
Example: http://m4q.org.ua/examples/vegas/

**Comment by olton** [comment]
in Vegas.js you must update arguments in last line
from
```
})(window.jQuery || window.Zepto);
```
to
```
})(window.jQuery || window.Zepto || window.m4q);
```

**Comment by arjarn** [comment]
Great job !

This plugin is only thing I can't using Metro-m4q on my site : can play with it now ;)

I'm already upgrading lats line but have problem with $slides definition.

**Comment by olton** [comment]
@arjarn update your version m4q

**Comment by arjarn** [comment]
It's allright 
Sorry for my bad

**Comment by arjarn** [comment]
If i'm using last m4q repo : I having [object][object] in my screen after each slide.
But if I'm taking include code in your example : <script src="m4q/m4q.js"></script> all is ok...

**Comment by olton** [comment]
Maybe need flush browser cache?

**Comment by olton** [comment]
Sorry, this is my bug. Fixed. Update your m4q and check now.

**Comment by arjarn** [comment]
It's OK.  
Thanx.
