### ISSUE TITLE
Add feature to interact with data-role with M4Q Constructor

### ISSUE THREAD

**Issue by floppy69** [olton/dom#6]
Hello Sergey,

you written about M4Q constructor that you can interact with elements by their classes, id, names. Can M4Q be used to interact with data-role ?

ex : `$( "!carrousel" )` or `$( "!taginput" )`

**Comment by olton** [comment]
### 1.0.8
+ [x] Constructor: add short-tag for selecting by `data-role` with `@role`

**Comment by olton** [comment]
Example:
```
<div data-role="role1, role2">data-role 1</div>

<script>
    console.log($("@role1")); // length 1
    console.log($("@role")); // length 0
</script>
```
